org.gradle.jvmargs=-Xmx4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED

org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true

# 依赖仓库与 Gradle 分发使用腾讯镜像加速；海外环境设为 false
useChineseMirror=true
